WARNING:dronekit:Link timeout, no heartbeat in last 5 seconds
WARNING:dronekit:Link timeout, no heartbeat in last 5 seconds
ERROR:dronekit.mavlink:Exception in MAVLink input loop
Traceback (most recent call last):
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
ERROR:dronekit.mavlink:Exception in MAVLink input loop
Traceback (most recent call last):
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
Traceback (most recent call last):
  File "/home/kinetic-indowings/YoloV11-Ultralytics/modified_strike.py", line 37, in <module>
    vehicle = connect('127.0.0.1:14550', wait_ready=True)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
Traceback (most recent call last):
  File "/home/kinetic-indowings/YoloV11-Ultralytics/modified_strike.py", line 37, in <module>
    vehicle = connect('127.0.0.1:14550', wait_ready=True)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/home/kinetic-indowings/.local/lib/python3.10/site-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
